version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run tests
          command: pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml
  e2e-playwright:
    docker:
      - image: mcr.microsoft.com/playwright:v1.44.1-jammy
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install Playwright browsers
          command: npx playwright install --with-deps
      - run:
          name: Run Playwright end-to-end tests
          command: npx playwright test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  build-and-test:
    jobs:
      - test-python
      - e2e-playwright:
          requires:
            - test-python
